# Generated by Django 4.0.3 on 2022-03-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_favorite'),
        ('goods', '0002_remove_goods_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='account.profile'),
        ),
        migrations.AddField(
            model_name='goods',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile'),
        ),
    ]
