# Generated by Django 4.0.3 on 2022-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goods_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='product',
            new_name='goods',
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='goods_photo'),
        ),
    ]
