# Generated by Django 4.0.3 on 2022-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_favorite'),
        ('goods', '0005_rename_product_goodsimage_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='account.profile'),
        ),
    ]
