# Generated by Django 4.0.3 on 2022-03-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
    ]
