# Generated by Django 4.0.3 on 2022-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
